### ISSUE TITLE
Code review #1

### ISSUE THREAD

**Issue by tshemsedinov** [yaryna-bashchak/snakes-and-ladders#1]
- Optimize with ternary: https://github.com/yaryna-bashchak/snakes-and-ladders/blob/48d9977ed41ebf6f6c0c0c719eaa9707ce7c0461/JavaScript/game.js#L23-L27
- Extract function `random`: https://github.com/yaryna-bashchak/snakes-and-ladders/blob/48d9977ed41ebf6f6c0c0c719eaa9707ce7c0461/JavaScript/game.js#L54 and https://github.com/yaryna-bashchak/snakes-and-ladders/blob/48d9977ed41ebf6f6c0c0c719eaa9707ce7c0461/JavaScript/game.js#L77
- Creaate a function from expression https://github.com/yaryna-bashchak/snakes-and-ladders/blob/48d9977ed41ebf6f6c0c0c719eaa9707ce7c0461/JavaScript/game.js#L42-L43

**Comment by yaryna-bashchak** [comment]
fixed it
